release:
  templates:
    - name: release
      title: "{tag}"
      exec:
        - make build-all
      files:
        - name: ucloud-cli-{tag}-darwin_amd64.zip
          path: out/darwin_amd64
        - name: ucloud-cli-{tag}-darwin_arm64.zip
          path: out/darwin_arm64
        - name: ucloud-cli-{tag}-linux_amd64.zip
          path: out/linux_amd64
        - name: ucloud-cli-{tag}-linux_arm64.zip
          path: out/linux_arm64
        - name: ucloud-cli-{tag}-windows_amd64.zip
          path: out/windows_amd64

